### ISSUE TITLE
Search in Question Items: cases-sensitive

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#176]
In current QDDT the search in QuestionItem is case sensitive.

It should not be case sensitive. It works for categories

**Comment by liuy97** [comment]
@BenjaminNSD 
There is no difference between searching category and searching questionitem at the frontend. It's backend to return result without case-intensive. The problem is that the result of searching categories is without case-intensive. But the result of searching questionitems is case-intensive.

**Comment by StigNorland** [comment]
I can fix that.

**Comment by StigNorland** [comment]
Will be included in next release
