### ISSUE TITLE
QuestionItem: make reuse of responsedomain user friendly

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#188]
Sarah wishes: Scroll down feature to select a response domain to add is not very user friendly .
 This applies to left menu and from concept window

Stig provides proposal

**Comment by StigNorland** [comment]
To solve this we would need to change our fundamental approach to solving the GUI. There is a limit of 1 modal window (focused window) in our chosen technology (and it makes sense).
Thus we cannot have several windows on top of each other. The modal window is out approach to filling in sub tasks, and in order to fix this we would need to change the way the whole app is working. 
Unfortunately this cannot be done before the end of this month.

@BenjaminNSD 

However, in QuestionItem, where this should be done, I suggest removing the option of creating response domain and the search functionality should be the only choice in this window.
![skjermbilde 2016-11-02 11 04 46](https://cloud.githubusercontent.com/assets/3939393/19924615/f7278a86-a0ec-11e6-9ecd-26a6d7fcd68d.png)

**Comment by StigNorland** [comment]
@BenjaminNSD , Would you concider this issue for sovled now?

**Comment by BenjaminNSD** [comment]
YEs, thanks!
