### ISSUE TITLE
Bug in QuestionItem/timestamp: when attaching a concept to QI

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#218]
I created a new question "test 11"  version 1.0 Then I attached this question to a concept. Afterwards I checked timestamp for the QuestionItem. Version 1.0 appears twice

![bug_timestamp](https://cloud.githubusercontent.com/assets/20127077/20307962/2b1fb174-ab42-11e6-9ae4-fae196f6a505.PNG)

**Comment by StigNorland** [comment]
I will fix it as it is confusing, but it is technical correct. 
QuestionItem isn't changed in anyway by attaching it to a concept (that includes save reason and changekind), but since it is a change in relationship the revision system has to keep a copy of this element by this save.
By modifying status, the element is changed, but this is absolutely more sensible for a user perspective.
