### ISSUE TITLE
Bug in saving of Question Items when attachinng missing value domain

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#281]
1. Tried to edit question "What is your personal attitude towards members of the following religious groups?" in questions (v1.0)
2. Then I added a Missing "CAN'T CHOOSE"
3. The I save as new major version.
4. After clicking submit I wasn't directed back to the table, instead the old version was displayed
5. No new version has been savend

**Comment by StigNorland** [comment]
bug in saving occured due to implementation of ArrayList (losts of empty elements)

**Comment by StigNorland** [comment]
bug is due to a new responsdomain is created and the revisionnumber isn't cleard out, resulting in a query to the backend where an ID and a rev number is queried that doesn't match (the new id doesn't have this revisionnumber). Errormessage from JPA is braindead as usually.
New issuse created for Yong to fix frontend.
