### ISSUE TITLE
System crashes when selecting certain domains in questions

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#354]
In questions. 
![crash](https://cloud.githubusercontent.com/assets/20127077/22826664/d3d09672-ef93-11e6-8739-1e82ed1e9e18.PNG)
When selecting scale domain called "test", the system crashes

**Comment by liuy97** [comment]
The reason is that the response domain has a code value with **null**. I can check null value at the front end. However, it should not allowed null value in the anchor at the API.

![screenshot from 2017-02-10 13-28-16](https://cloud.githubusercontent.com/assets/2961144/22826854/e1573b1a-ef94-11e6-9210-2c5fe54d7ddc.png)
