### ISSUE TITLE
Publication status: Elements in select buisiness version view 

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#383]
Please see the below
![elements in select business view](https://cloud.githubusercontent.com/assets/10205366/23754033/d92bceae-04db-11e7-8f96-4d50a2948fb8.PNG)

**Comment by StigNorland** [comment]
@liuy97 
backend qddt.test now returns publication with PublicationElement.element set.
NB added 2 fields to PublicationElement name and version, purpose is name and version of element selected.
backend doens't do anything with these fields.

**Comment by liuy97** [comment]
You add two fields, name and version. Are they setup at the frontend?

```
purpose is name and version of element selected.
```
What does it mean?

![screenshot from 2017-03-22 13-20-23](https://cloud.githubusercontent.com/assets/2961144/24197552/5b2ff95e-0f02-11e7-8168-9bb854c0cecc.png)

**Comment by StigNorland** [comment]
in contentlist you have 2 columns :	Element name	and Version
I added these to the backend, and thought the front end could populate them, since backend doesn't know thier content before loading the element from revision history, which it doesn't do before you ask for details.
However I just added code to populate them, this is however kind of backward, since it is only populated when the element-details are returned.

**Comment by StigNorland** [comment]
as you can just fetch this from the returning elements there is little point in doing this in the "detail view" of publication...

**Comment by StigNorland** [comment]
if it is unclear what I mean, just forget it...
