### ISSUE TITLE
Browser versions and browser settings

### ISSUE THREAD

**Issue by kksnsd** [DASISH/qddt-client#42]
If app functionalities depend on browser, browser versions and browser settings, we have to inform people at HQ and NSD about it

**Comment by StigNorland** [comment]
Any new browser should work, Safari, Chrome,Firefox, IE, Edge or Opera
When you install the latest version of any of these browsers, they will keep themselves updated, old browsers don't have this functionality.
Haven't tested Safari and Edge.

**Comment by liuy97** [comment]
It's better to list the minimal versions of the browsers. 

The information from http://angularjs.blogspot.no/2014/03/angular-20.html

> We’re designing AngularJS 2 for the way the world will look when we believe folks will use it.  In particular, this means targeting modern browsers and using ECMAScript 6.
> Modern Browsers
> Modern browsers means the set of browsers known as ‘evergreen’ or always automatically updated to the latest version.  Building for these browsers let us drop many hacks and workarounds that make AngularJS harder to use and develop on than it needs to be.
> 
> The set currently includes Chrome, FireFox, Opera, Safari, and IE10/11.  On mobile, we’ll support something close to the list of Chrome on Android, iOS 6+, Windows Phone 8+ and Firefox mobile.  We’re looking into supporting older versions of Android, but the jury is still out. 

The following information from the seed project used by qddt-client:
1. ie >= 10,
2. ie_mob >= 10,
3.  ff >= 30,
4. chrome >= 34,
5.  safari >= 7,
6.  opera >= 23,
7.  ios >= 7,
8.  android >= 4.4,

However, IE 10 does not work well, because of the CORS problem I have reported.
