### ISSUE TITLE
How to create a missing domain

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#82]
Refs #76,

How to create a missing domain?

**Comment by hildeorten** [comment]
ManagedMissingValuesRepresentation: Type definition in DDI: Means of 
describing the Missing Values within a managed representation so that 
they can be reused by multiple variables and questions. Variable has a 
separate Missing Values location for this representation. Questions must 
use a StructuredMixedResponseDomain to include both standard response 
and Missing Value responses in a single question. In addition to the 
name, label, and description of the representation, the structure 
defines the type of the missing values, a optional generation 
instruction for deriving the value to be recorded, and the ability to 
define a blank as a missing value

For now – please implement MissingCodeRepresentation for this, as this 
has priority in the ESS
http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/schemas/reusable_xsd/elements/MissingCodeRepresentation.html

The missing representation can be implemented in it’s own page, 
accessible from the response domain page, like the scale domain or code 
domain. But it shold not be possible to reference it as a single 
response domain in the QuestionItem. Only in the mixed domain

Den 2016-07-18 14:32 skreiv liuy97:

**Comment by liuy97** [comment]
Thank @hildeorten for your reply during holiday. This issue is related to Backend API (a technical problem): how to use API to create a missing response domain.

**Comment by StigNorland** [comment]
It was already implemented before I went on holliday, what happened?

**Comment by liuy97** [comment]
If it has been implemented, please update your wiki, or give me an example if possible. As far as I know, you use a missing category instead of a missing response domain. Is it right?

**Comment by StigNorland** [comment]
All "groups" of categories ( LIST,SCALE, MIXED & MISSING_GROUP) are created the same way, using the same principles. 
It is the category hierarchy that defines both the managed representation and response domain.

it is defined by  "categoryType" : "MISSING_GROUP"

**Comment by liuy97** [comment]
So no missing response domain at all. There is only a missing category.

**Comment by StigNorland** [comment]
I kind of regret putting response_kind into responsedomain, as it would be sufficient to read the category.
but yes these are the following ResponseKind in the backend.
    DATETIME,
    TEXT,
    NUMERIC,
    LIST,
    SCALE,
    MIXED
there is no missing as it is not a valid responsdomain (you can't have just different missing response to a question, you need answers as well.)

**Comment by liuy97** [comment]
Refs #76, a missing response domain is mentioned. I also read that file. That's why I create this issue for confirming this problem. Now I will write the following sentences:
A missing response domain will not be supported, because the backend API does not support it. Instead of a missing response domain, a missing categories will be supposed to use.
