### ISSUE TITLE
Scale domain support vertical and horizontal direction

### ISSUE THREAD

**Issue by liuy97** [DASISH/qddt-client#96]
Refs #29,

The output direction will be implemented in scale domain firstly.

**Comment by hildeorten** [comment]
@liuy97 

In DDI the attribute degreeSlopeFromHorizontal is defined as <A horizontal line is described as a 0 (zero) slope. Expressed as the number of degrees positive (right end angle above the horizontal line) or degrees positive (right end descending below the horizontal line)>. 

For us 90 degrees would probably be enough, or horizontal vs. vertical. (We can start with this, I'll check if further info is needed).

You can enter possibilities to enter this information for scale domain, but the graphical layout to be able to turn the scale will need to wait till later. 

Otherwise, for now please implement the changes. Option to enter changes proposed in the attached document.
[ScaleDomain_ho_1.docx](https://github.com/DASISH/qddt-client/files/385881/ScaleDomain_ho_1.docx)
